config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :m_jurusans, :m_prodis, :m_nilais
  end
  # resources :m_jurusans
  # resources :m_prodis
  # resources :m_nilais
  root 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/m_jurusan.rb
class MJurusan < ApplicationRecord
  validates :id_jurusan, :presence => true, :uniqueness => true
  validates :nama_jurusan, :singkatan, :email_jurusan,
            :telp_jurusan, :situs_jurusan, :tanggal_berdiri,
            :sk_berdiri, presence: true
  validates :nama_jurusan, length: { minimum: 7 }
  validates :id_jurusan, :numericality => true
  has_many :m_prodis, dependent: :destroy
end

app/models/m_nilai.rb
class MNilai < ApplicationRecord
end

app/models/m_prodi.rb
class MProdi < ApplicationRecord
  belongs_to :m_jurusan
end

app/controllers/admin/m_jurusans_controller.rb
module Admin
  class MJurusansController < ApplicationController
    before_action :find_jurusan, only: [:show, :edit, :update, :destroy]

    def index
      @jurusans = MJurusan.all
    end

    def show
    end

    def new
      @jurusan = MJurusan.new
    end


    def create
      @jurusan = MJurusan.new(jurusan_params)
      if @jurusan.valid?
        if @jurusan.save
          redirect_to admin_m_jurusans_path
        end
      else
        render 'new'
      end
    end

    def edit
    end

    def update
      if @jurusan.update(jurusan_params)
        redirect_to admin_m_jurusan_path(@jurusan)
      else
        render 'edit'
      end
    end

    def destroy
      @jurusan.destroy
      redirect_to admin_m_jurusans_path
    end

    private

    def jurusan_params
      params.require(:m_jurusan).permit(:id_jurusan, :nama_jurusan, :singkatan, :email_jurusan,
                                        :telp_jurusan, :situs_jurusan, :tanggal_berdiri, :sk_berdiri)
    end

    def find_jurusan
      @jurusan = MJurusan.find(params[:id])
    end

  end
end

app/controllers/admin/m_nilais_controller.rb
module Admin
  class MNilaisController < ApplicationController
    def index
      @nilais = MNilai.all.order(:id)
    end

    def new
      @nilai = MNilai.new
    end

    def create
      @nilai = MNilai.new(nilai_params)
      if @nilai.valid?
        if @nilai.save
          redirect_to m_nilais_path
        end
      else
        render 'new'
      end
    end

    private

    def nilai_params
      params.require(:m_nilai).permit(:nilai_huruf, :bobot, :skala)
    end

    def find_jurusan
      @nilai = MNilai.find(params[:id])
    end

  end
end

app/controllers/admin/m_prodis_controller.rb
module Admin
  class MProdisController < ApplicationController
    before_action :find_prodi, only: [:show, :edit, :update, :destroy]

    def index
      @prodis = MProdi.all
    end

    def new
      @prodi = MProdi.new
    end

    def create
      @prodi = MProdi.new(prodi_params)
      if @prodi.valid?
        if @prodi.save
          redirect_to m_prodis_path
        end
      else
        render 'new'
      end
    end

    def show
    end

    def edit
    end

    def update
      if @prodi.update(prodi_params)
        redirect_to m_prodi_path(@prodi)
      else
        render 'edit'
      end
    end

    def destroy
      @prodi.destroy
      redirect_to m_prodis_path
    end

    private

    def prodi_params
      params.require(:m_prodi).permit(:id_prodi, :nama_prodi, :m_jurusan_id, :email_prodi,
                                      :telp_prodi, :situs_prodi, :tanggal_berdiri, :sk_berdiri)
    end

    def find_prodi
      @prodi = MProdi.find(params[:id])
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/m_jurusans_helper.rb
module MJurusansHelper
end

app/helpers/m_nilais_helper.rb
module MNilaisHelper
end

app/helpers/m_prodis_helper.rb
module MProdisHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/m_jurusans/_form.html.erb
  <%= simple_form_for [:admin, @jurusan] do |f| %>
      <%= f.input :id_jurusan, label: 'ID Jurusan', hint: 'Masukkan 1-5' %>
      <%= f.input :nama_jurusan, label: 'Jurusan' %>
      <%= f.input :singkatan %>
      <%= f.input :email_jurusan, label: 'Email Jurusan' %>
      <%= f.input :telp_jurusan, label: 'Telepon Jurusan' %>
      <%= f.input :situs_jurusan, label: 'Situs Jurusan' %>
      <%= f.input :tanggal_berdiri, label: 'Tanggal Berdiri', as: :date, order: [:day, :month, :year] %>
      <%= f.input :sk_berdiri, label: 'SK Berdiri' %>
      <center>
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
      <%= button_tag "Reset", type: :reset, class: 'btn btn-danger' %>
      </center>
  <% end %>

app/views/admin/m_jurusans/edit.html.erb
<div class="container">
  Edit Jurusan <br>
  <%= render 'form' %>
</div>

app/views/admin/m_jurusans/index.html.erb
<div class="container">

  <% @jurusans.each do |jurusan| %>
      <h1><%= link_to jurusan.nama_jurusan, admin_m_jurusan_path(jurusan) %></h1>
      <h2><%= jurusan.singkatan %></h2>
      <hr>
  <% end %>

  <%= link_to 'New Item', new_admin_m_jurusan_path, class: 'btn btn-warning' %>
</div>

app/views/admin/m_jurusans/new.html.erb
<div class="container">
  Input Jurusan <br>
  <%= render 'form' %>
</div>

app/views/admin/m_jurusans/show.html.erb
<div class="col-md-10 col-md-offset-1">

  <h2><%= @jurusan.nama_jurusan %></h2>
  <hr>
  <p>ID Jurusan : <%= @jurusan.id_jurusan %></p>
  <br>
  <p>Singkatan : <%= @jurusan.singkatan %></p>
  <br>
  <p>Email : <%= @jurusan.email_jurusan %></p>
  <br>
  <p>Telepon Jurusan : <%= @jurusan.telp_jurusan %></p>
  <br>
  <p>Situs Jurusan : <%= @jurusan.situs_jurusan %></p>
  <br>
  <p>Tanggal berdiri : <%= @jurusan.tanggal_berdiri.to_date.to_s %></p>
  <br>
  <p>SK Berdiri : <%= @jurusan.sk_berdiri %></p>
  <br>
  <p>Program Studi : </p>
  <ol>
  <% @jurusan.m_prodis.each do |prodi| %>
    <li><%= prodi.nama_prodi %></li>
  <% end %>
  </ol>
  <hr>
  <div class="col-md-4 col-md-offset-4">
    <center>
    <%= link_to "Back", admin_m_jurusans_path %>
    <%= link_to "Edit", edit_admin_m_jurusan_path(@jurusan) %>
    <%= link_to "Delete", admin_m_jurusan_path(@jurusan), method: :delete, data: {confirm: "Are you sure ?"} %>
    </center>
  </div>
</div>

app/views/admin/m_nilais/_form.html.erb
<%= simple_form_for [:admin, @nilai] do |f| %>
    <%= f.input :nilai_huruf, label: 'Nilai' %>
    <%= f.input :skala %>
    <%= f.input :bobot %>
    <center>
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
      <%= button_tag "Reset", type: :reset, class: 'btn btn-danger' %>
    </center>
<% end %>

app/views/admin/m_nilais/index.html.erb
<div class="container">
  <center><h1>Daftar nilai</h1></center>
  <% @nilais.each do |nilai| %>
      <%= nilai.nilai_huruf %>
       | <%= nilai.skala %>
       | <%= nilai.bobot %>
      <br>
  <% end %>
  <hr>
  <%= link_to 'New Item', new_admin_m_nilai_path, class: 'btn btn-warning' %>
</div>

app/views/admin/m_nilais/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/admin/m_prodis/_form.html.erb
<%= simple_form_for [:admin, @prodi] do |f| %>
    <%= f.input :id_prodi, label: 'ID Prodi', hint: 'Masukkan 1-5' %>
    <%= f.input :nama_prodi, label: 'Prodi' %>
    <%= f.association :m_jurusan, label_method: :nama_jurusan, include_blank: false %>
    <%= f.input :email_prodi, label: 'Email Prodi' %>
    <%= f.input :telp_prodi, label: 'Telepon Prodi' %>
    <%= f.input :situs_prodi, label: 'Situs Prodi' %>
    <%= f.input :tanggal_berdiri, label: 'Tanggal Berdiri', as: :date, order: [:day, :month, :year] %>
    <%= f.input :sk_berdiri, label: 'SK Berdiri' %>
    <center>
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
      <%= button_tag "Reset", type: :reset, class: 'btn btn-danger' %>
    </center>
<% end %>

app/views/admin/m_prodis/edit.html.erb
<div class="container">
  Edit Prodi <br>
  <%= render 'form' %>
</div>

app/views/admin/m_prodis/index.html.erb
<div class="container">
  <% @prodis.each do |prodi| %>
      <h1><%= link_to prodi.nama_prodi, admin_m_prodi_path(prodi) %></h1>
      <h2><%= prodi.m_jurusan_id %></h2>
      <hr>
  <% end %>

  <%= link_to 'New Item', new_admin_m_prodi_path, class: 'btn btn-warning' %>
</div>

app/views/admin/m_prodis/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/admin/m_prodis/show.html.erb
<div class="col-md-10 col-md-offset-1">

  <h2><%= @prodi.nama_prodi %></h2>
  <hr>
  <p>ID Prodi : <%= @prodi.id_prodi %></p>
  <br>
  <p>Jurusan : <%= @prodi.m_jurusan.nama_jurusan %></p>
  <br>
  <p>Email : <%= @prodi.email_prodi %></p>
  <br>
  <p>Telepon Jurusan : <%= @prodi.telp_prodi %></p>
  <br>
  <p>Situs Jurusan : <%= @prodi.situs_prodi %></p>
  <br>
  <p>Tanggal berdiri : <%= @prodi.tanggal_berdiri.to_date.to_s %></p>
  <br>
  <p>SK Berdiri : <%= @prodi.sk_berdiri %></p>
  <hr>
  <div class="col-md-4 col-md-offset-4">
    <center>
      <%= link_to "Back", admin_m_prodis_path %>
      <%= link_to "Edit", edit_admin_m_prodi_path(@prodi) %>
      <%= link_to "Delete", admin_m_prodi_path(@prodi), method: :delete, data: {confirm: "Are you sure ?"} %>
    </center>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sikad</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to "Home",root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Jurusan", admin_m_jurusans_path %></li>
            <li><%= link_to "Prodi", admin_m_prodis_path %></li>
            <li><%= link_to "Nilai", admin_m_nilais_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/m_jurusans/_form.html.erb
  <%= simple_form_for @jurusan do |f| %>
      <%= f.input :id_jurusan, label: 'ID Jurusan', hint: 'Masukkan 1-5' %>
      <%= f.input :nama_jurusan, label: 'Jurusan' %>
      <%= f.input :singkatan %>
      <%= f.input :email_jurusan, label: 'Email Jurusan' %>
      <%= f.input :telp_jurusan, label: 'Telepon Jurusan' %>
      <%= f.input :situs_jurusan, label: 'Situs Jurusan' %>
      <%= f.input :tanggal_berdiri, label: 'Tanggal Berdiri', as: :date, order: [:day, :month, :year] %>
      <%= f.input :sk_berdiri, label: 'SK Berdiri' %>
      <center>
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
      <%= button_tag "Reset", type: :reset, class: 'btn btn-danger' %>
      </center>
  <% end %>

app/views/m_jurusans/show.html.erb
<div class="col-md-10 col-md-offset-1">

  <h2><%= @jurusan.nama_jurusan %></h2>
  <hr>
  <p>ID Jurusan : <%= @jurusan.id_jurusan %></p>
  <br>
  <p>Singkatan : <%= @jurusan.singkatan %></p>
  <br>
  <p>Email : <%= @jurusan.email_jurusan %></p>
  <br>
  <p>Telepon Jurusan : <%= @jurusan.telp_jurusan %></p>
  <br>
  <p>Situs Jurusan : <%= @jurusan.situs_jurusan %></p>
  <br>
  <p>Tanggal berdiri : <%= @jurusan.tanggal_berdiri.to_date.to_s %></p>
  <br>
  <p>SK Berdiri : <%= @jurusan.sk_berdiri %></p>
  <br>
  <p>Program Studi : </p>
  <ol>
  <% @jurusan.m_prodis.each do |prodi| %>
    <li><%= prodi.nama_prodi %></li>
  <% end %>
  </ol>
  <hr>
  <div class="col-md-4 col-md-offset-4">
    <center>
    <%= link_to "Back", m_jurusans_path %>
    <%= link_to "Edit", edit_m_jurusan_path(@jurusan) %>
    <%= link_to "Delete", m_jurusan_path(@jurusan), method: :delete, data: {confirm: "Are you sure ?"} %>
    </center>
  </div>
</div>

app/views/m_nilais/_form.html.erb
<%= simple_form_for @nilai do |f| %>
    <%= f.input :nilai_huruf, label: 'Nilai' %>
    <%= f.input :skala %>
    <%= f.input :bobot %>
    <center>
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
      <%= button_tag "Reset", type: :reset, class: 'btn btn-danger' %>
    </center>
<% end %>

app/views/m_nilais/index.html.erb
<div class="container">
  <center><h1>Daftar nilai</h1></center>
  <% @nilais.each do |nilai| %>
      <%= nilai.nilai_huruf %>
       | <%= nilai.skala %>
       | <%= nilai.bobot %>
      <br>
  <% end %>
  <hr>
  <%= link_to 'New Item', new_m_nilai_path, class: 'btn btn-warning' %>
</div>

app/views/m_prodis/_form.html.erb
<%= simple_form_for @prodi do |f| %>
    <%= f.input :id_prodi, label: 'ID Prodi', hint: 'Masukkan 1-5' %>
    <%= f.input :nama_prodi, label: 'Prodi' %>
    <%= f.association :m_jurusan, label_method: :nama_jurusan, include_blank: false %>
    <%= f.input :email_prodi, label: 'Email Prodi' %>
    <%= f.input :telp_prodi, label: 'Telepon Prodi' %>
    <%= f.input :situs_prodi, label: 'Situs Prodi' %>
    <%= f.input :tanggal_berdiri, label: 'Tanggal Berdiri', as: :date, order: [:day, :month, :year] %>
    <%= f.input :sk_berdiri, label: 'SK Berdiri' %>
    <center>
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
      <%= button_tag "Reset", type: :reset, class: 'btn btn-danger' %>
    </center>
<% end %>

app/views/m_prodis/show.html.erb
<div class="col-md-10 col-md-offset-1">

  <h2><%= @prodi.nama_prodi %></h2>
  <hr>
  <p>ID Prodi : <%= @prodi.id_prodi %></p>
  <br>
  <p>Jurusan : <%= @prodi.m_jurusan.nama_jurusan %></p>
  <br>
  <p>Email : <%= @prodi.email_prodi %></p>
  <br>
  <p>Telepon Jurusan : <%= @prodi.telp_prodi %></p>
  <br>
  <p>Situs Jurusan : <%= @prodi.situs_prodi %></p>
  <br>
  <p>Tanggal berdiri : <%= @prodi.tanggal_berdiri.to_date.to_s %></p>
  <br>
  <p>SK Berdiri : <%= @prodi.sk_berdiri %></p>
  <hr>
  <div class="col-md-4 col-md-offset-4">
    <center>
      <%= link_to "Back", m_prodis_path %>
      <%= link_to "Edit", edit_m_prodi_path(@prodi) %>
      <%= link_to "Delete", m_prodi_path(@prodi), method: :delete, data: {confirm: "Are you sure ?"} %>
    </center>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Dashboard</h1>
  </div>
</div>